### ISSUE TITLE
Column names with TEXT format

### ISSUE THREAD

**Issue by henshin** [dcmoura/spyql#62]
When using TEXT as an import format, I couldn't find a way of configuring the column name. The column name seems to be evaluated as long as we don't specify `*` in the SELECT statement which we have to do for TEXT files. Am I missing something?
Here's an example:
```
cat /tmp/test.txt | spyql -Otable=domains 'Select * as colname from text To SQL'
INSERT INTO "domains"("col1") VALUES ('aaaaaaaaaa'),('bbbbbbbbb'),('cccccccccc'),('dddddddddd'),('eeeeeeeeee');
```

```
cat /tmp/test.txt | spyql -Otable=domains 'Select 1 as colname from text To SQL' 
INSERT INTO "domains"("colname") VALUES (1),(1),(1),(1),(1);
```

Expected result would be:
```
cat /tmp/test.txt | spyql -Otable=domains 'Select * as colname from text To SQL'
INSERT INTO "domains"("colname") VALUES ('aaaaaaaaaa'),('bbbbbbbbb'),('cccccccccc'),('dddddddddd'),('eeeeeeeeee');
```

**Comment by dcmoura** [comment]
Can you please try the following?
```
cat /tmp/test.txt | spyql -Otable=domains 'Select col1 as colname from text To SQL'
```

Columns in spyql can be accessed by index using the syntax `colX` where `X` is the index of the column, starting in 1. So, `col1` gives you access to the 1st column. In the case of the `text` input format, there's only 1 input column and there isn't any other way to access it since the text input format does not support headers. 

The alias is ignored in `*`... probably spyql should report an error in your query...

**Comment by henshin** [comment]
Thanks, that worked! 
I would suggest add this info to the documentation for future reference.

**Comment by dcmoura** [comment]
Makes perfect sense :-) Thank you for trying out spyql!!
