### ISSUE TITLE
how to get distinct top level json keys

### ISSUE THREAD

**Issue by ivostoykov** [dcmoura/spyql#96]
Hello,

A great tool and has impressive performance! :-)

I am wondering whether there is a way to extract all top-level key names from a complex json file.
Using the below example, I need to extract 'a', 'b' and 'c' regardless of what the value is. An extra will be if I can distinct the result.

Thanks
Ivo
```
[
  {
    "a": 1,
    "b": 2,
    "c": [
      {
        "d": 3
      }
    ]
  },
  {
    "a": 10,
    "b": 20,
    "c": [
      {
        "d": 30
      }
    ]
  }
]
```

**Comment by ivostoykov** [comment]
Here's the solution I found. Comments are highly welcome:

`spyql "SELECT .keys() FROM json LIMIT 10 TO json" < input_file.jsonl > result.json`

Not distinct but allows to apply `set()` as well

**Comment by dcmoura** [comment]
Hello! Thank you for your feedback :-) 

Let's say your input data is:
```json
{"a":1,"b":2,"c":[{"d":3}]}
{"a":10,"b":20,"e":[{"d":30}]}
```


Your solution is on the right direction :-) You should convert the output of `keys()` to a list so that when exporting to JSON it is converted to a JSON array.

```sh
$ spyql "SELECT list(.keys()) AS key_list FROM json TO json" < data.jsonl

{"key_list": ["a", "b", "c"]}
{"key_list": ["a", "b", "e"]}
```

Then, we can aggregate all lists using a sum aggregation (summing lists in python concatenates them):

```sh
$ spyql "SELECT list(.keys()) AS key_list FROM json TO json" | spyql "SELECT sum_agg(.key_list) AS all_keys FROM json TO json" < data.jsonl

{"all_keys": ["a", "b", "c", "a", "b", "e"]}
```

Finally, you can convert the result of the sum to a set (to get the unique elements) and then convert it to a list (to output a JSON array):

```sh
$ spyql "SELECT list(.keys()) AS key_list FROM json TO json" | spyql "SELECT list(set(sum_agg(.key_list))) AS all_keys FROM json TO json" < data.jsonl

{"all_keys": ["a", "b", "c", "e"]}
```

Is this what you were looking for? 

Another way to do this, if you would like your output as CSV is to explode the JSON array and then do a DISTINCT:

```sh
$ spyql "SELECT list(.keys()) AS key_list FROM json TO json" | spyql "SELECT DISTINCT .key_list AS key FROM json EXPLODE .key_list" < data.jsonl

key
a
b
c
e
```

And there are more ways to do it :-)

**Comment by ivostoykov** [comment]
Hi @dcmoura ,

Thank you very much for your clear and comprehensive reply. Yes, that's what I was looking for. This tool saved me so much work. Great tool!

**Comment by dcmoura** [comment]
Thank you @ivostoykov, I am very happy that you are finding it useful :-)
